
inherit_from: configs/multi_view_reconstruction/birds/ours_depth_mvs.yaml
generation:
  generation_dir: generation_pretrained
test:
  model_file: https://drive.google.com/file/d/1CANeW0kNN30vicDxNw6sY1NaGvxd5XIM/view?usp=sharing
  #file uploaded at pico
  #model_file: https://s16.picofile.com/d/8423167926/c0f2be29-6c6c-411d-8704-91adfc402bb6/model_best.pt
