inherit_from: configs/multi_view_reconstruction/birds/ours_rgb.yaml
generation:
  generation_dir: generation_pretrained
test:
  model_file: https://s17.picofile.com/d/8423171384/9480829a-2d08-4f37-865e-0113613eef7a/model_best.pt
